name: Package .deb

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version name"
        required: true

env:
  INPUT_VERSION_NAME: ${{ github.event.inputs.version_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deb:
    # The host should always be Linux
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest armv7
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          # This is an old distro, but it's what Red pitaya runs upon
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            whoami
            pwd
            ls -l
            #echo ${{ github.event.inputs.version_name }} > linien-server/VERSION

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          ls -l

      # - uses: actions/upload-artifact@v2
        # with:
          # name: 
          # path: dist/linux
